--SET FOREIGN_KEY_CHECKS=0;
--DROP VIEW credit_scoring.DELINQUENCY_MODEL_VIEW;

CREATE view credit_scoring.DELINQUENCY_MODEL_VIEW as select
  `DELIQUENCY_MODEL_ID`,
  `ACTION` ,
  `CANBLACKLIST` ,
  `CANDEFAULT` ,
  `CANSUSPEND` ,
  `DAYS_AFTER_DEFAULT`,
  `DAYS_TO_SUSPENSION` ,
  delinquency_model.INTRASH ,
  `PENALTY` ,
--  `PRODUCT_NAME`,
  `PENALTY_TYPE` ,
  `PERIOD` ,
  `PRODUCT_ID_FK`
  from DELINQUENCY_MODEL
  join product
  on delinquency_model.PRODUCT_ID_FK = product.PRODUCT_ID;
--  SET FOREIGN_KEY_CHECKS=1;