CREATE TABLE `BUSINESS_TYPE` (
  `ID` int PRIMARY KEY NOT NULL,
  `CREATED_BY_FK` int DEFAULT NULL,
  `DATE_CREATED` datetime DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `INTRASH` varchar(255) DEFAULT NULL,
  `TYPE` varchar(255) DEFAULT NULL
) ENGINE=InnoDB;

CREATE TABLE `Organisation` (
  `ORGANISATION_ID` int PRIMARY KEY NOT NULL,
  `BUSINESS_TYPE_FK` int NOT NULL,
  `CREATED_BY` int DEFAULT NULL,
  `DATE_CREATED` datetime DEFAULT NULL,
  `EMAIL_ADDRESS` varchar(255) DEFAULT NULL,
  `INTRASH` varchar(255) DEFAULT NULL,
  `MSISDN` varchar(255) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `ORG_CODE` varchar(255) DEFAULT NULL,
  `PHYSICAL_ADDRESS` varchar(255) DEFAULT NULL,
  `STATUS` int DEFAULT NULL,
  FOREIGN KEY (`BUSINESS_TYPE_FK`) REFERENCES `business_type` (`ID`)
) ENGINE=InnoDB ;

CREATE TABLE `Config` (
  `ID` int PRIMARY KEY NOT NULL,
  `CATEGORY` varchar(255) DEFAULT NULL,
  `CREATED_BY` int DEFAULT NULL,
  `LARGE_VALUE` varchar(255) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `ORGANISATION_ID_FK` int DEFAULT NULL,
  `TIME_CREATED` datetime DEFAULT NULL,
  `TIME_UPDATED` datetime DEFAULT NULL,
  `UPDATED_BY` int DEFAULT NULL,
  `VALUE` varchar(255) DEFAULT NULL,
FOREIGN KEY (`ORGANISATION_ID_FK`) REFERENCES `organisation` (`ORGANISATION_ID`)
) ENGINE=InnoDB ;

CREATE TABLE `DATA_SOURCE` (
  `DATA_SOURCE_ID` int PRIMARY KEY NOT NULL,
  `ACTION` varchar(255) DEFAULT NULL,
  `APPROVAL_LEVEL` int DEFAULT NULL,
  `APPROVAL_STATUS` int DEFAULT NULL,
  `CREATED_BY` int DEFAULT NULL,
  `DATA_SOURCE_TYPE` varchar(255) DEFAULT NULL,
  `DATA_SOURCE_URL` varchar(255) DEFAULT NULL,
  `DATA_USAGE` varchar(255) DEFAULT NULL,
  `DATE_CREATED` datetime DEFAULT NULL,
  `EXCEL_PATH` varchar(255) DEFAULT NULL,
  `EXCEL_URL` varchar(255) DEFAULT NULL,
  `EXPIRY` datetime DEFAULT NULL,
  `INTRASH` varchar(255) DEFAULT NULL,
  `KYC_ID` int DEFAULT NULL,
  `MAX_APPROVALS`int DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `ORGANISATION_ID_FK` int DEFAULT NULL,
  `SCORING_DATA_SIZE` int DEFAULT NULL,
  `STATUS` int DEFAULT NULL,
  `UPDATE_CYCLE` int DEFAULT NULL,
  `ORGANISATION` varchar(255) DEFAULT NULL,
FOREIGN KEY (`ORGANISATION_ID_FK`) REFERENCES `organisation` (`ORGANISATION_ID`)
) ENGINE=InnoDB ;

CREATE TABLE `Program` (
  `PROGRAM_ID` int PRIMARY KEY NOT NULL,
  `CREATED_BY` int DEFAULT NULL,
  `DATA_SOURCE_ID_FK` int DEFAULT NULL,
  `DATE_CREATED` datetime DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `INTRASH` varchar(255) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `ORGANISATION_ID_FK` int DEFAULT NULL,
  `PRIMARY_IDENTITY_TYPE` varchar(255) DEFAULT NULL,
  `STATUS` int DEFAULT NULL,
  `DATA_SOURCE` varchar(255) DEFAULT NULL,
  `ORGANISATION` varchar(255) DEFAULT NULL,
FOREIGN KEY (`ORGANISATION_ID_FK`) REFERENCES `organisation` (`ORGANISATION_ID`)
) ENGINE=InnoDB ;

CREATE TABLE `Product` (
  `PRODUCT_ID` int  PRIMARY KEY NOT NULL,
  `ARMOTIZED` int DEFAULT NULL,
  `ATTACHED_SUPPLIER_ID` varchar(255) DEFAULT NULL,
  `AUTOMATED_SCORING` int DEFAULT NULL,
  `CBS_PRODUCT` varchar(255) DEFAULT NULL,
  `CREATED_BY` int DEFAULT NULL,
  `DATE_CREATED` datetime DEFAULT NULL,
  `INSTALLMENT_OPTIONS` varchar(255) DEFAULT NULL,
  `INSTALLMENT_PERIOD` int DEFAULT NULL,
  `INTEREST_RATE` double DEFAULT NULL,
  `INTEREST_TYPE` varchar(255) DEFAULT NULL,
  `INTEREST_UPFRONT` double DEFAULT NULL,
  `INTRASH` varchar(255) DEFAULT NULL,
  `LOAN_LIMIT_LOAN_AMOUNT_CAP` double DEFAULT NULL,
  `LOAN_LIMIT_LOAN_NUM_CAP` double DEFAULT NULL,
  `MAX_AMOUNT` double DEFAULT NULL,
  `MAX_REPAY_PERIOD` int DEFAULT NULL,
  `MIN_AMOUNT` double DEFAULT NULL,
  `MIN_REPAY_PERIOD` int DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `PERIOD_UNITS` varchar(255) DEFAULT NULL,
  `PROGRAM_ID_FK` int DEFAULT NULL,
  `RECIPIENT_TYPE` varchar(255) DEFAULT NULL,
  `REDUCING_BALANCE` double DEFAULT NULL,
  `STATUS` int DEFAULT NULL,
  `TAKE_CHARGES_UPFRONT` double DEFAULT NULL,
  `UPDATE_CYCLE` int DEFAULT NULL,
  `ORGANISATION_ID_FK` int DEFAULT NULL,
  `PROGRAM_NAME` varchar(255) DEFAULT NULL,
FOREIGN KEY (`PROGRAM_ID_FK`) REFERENCES `program` (`PROGRAM_ID`),
FOREIGN KEY (`ORGANISATION_ID_FK`) REFERENCES `organisation` (`ORGANISATION_ID`)
) ENGINE=InnoDB ;

CREATE TABLE `DELINQUENCY_MODEL` (
  `DELIQUENCY_MODEL_ID` int PRIMARY KEY NOT NULL,
  `ACTION` varchar(255) DEFAULT NULL,
  `CANBLACKLIST` int DEFAULT NULL,
  `CANDEFAULT` int DEFAULT NULL,
  `CANSUSPEND` int DEFAULT NULL,
  `DAYS_AFTER_DEFAULT` int DEFAULT NULL,
  `DAYS_TO_SUSPENSION` int DEFAULT NULL,
  `INTRASH` varchar(255) DEFAULT NULL,
  `PENALTY` int DEFAULT NULL,
  `PENALTY_TYPE` varchar(255) DEFAULT NULL,
  `PERIOD` int DEFAULT NULL,
  `PRODUCT_ID_FK` int DEFAULT NULL,
FOREIGN KEY (`PRODUCT_ID_FK`) REFERENCES `product` (`PRODUCT_ID`)
) ENGINE=InnoDB ;

CREATE TABLE `SCORE_CATEGORY_MASTER` (
  `SC_MASTER_ID` int PRIMARY KEY NOT NULL,
  `CONTRIBUTION` double DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `PRODUCT_ID_FK` int DEFAULT NULL,
  `USED` varchar(255) DEFAULT NULL,
  `PRODUCT_NAME` varchar(255) DEFAULT NULL,
FOREIGN KEY (`PRODUCT_ID_FK`) REFERENCES `product` (`PRODUCT_ID`)
) ENGINE=InnoDB ;

CREATE TABLE `SCORE_CATEGORY` (
  `SCORE_CATEGORY_ID` int PRIMARY KEY NOT NULL,
  `APPROVAL_LEVEL` int DEFAULT NULL,
  `APPROVAL_STATUS` int DEFAULT NULL,
  `CONTRIBUTION` double DEFAULT NULL,
  `INTRASH` varchar(255) DEFAULT NULL,
  `MAX_APPROVALS` int DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `PRODUCT_ID_FK` int DEFAULT NULL,
  `SC_MASTER_ID_FK` int DEFAULT NULL,
  `UPDATE_CYCLE` int DEFAULT NULL,
  `USED` varchar(255) DEFAULT NULL,
FOREIGN KEY (`PRODUCT_ID_FK`) REFERENCES `product` (`PRODUCT_ID`),
FOREIGN KEY (`SC_MASTER_ID_FK`) REFERENCES `score_category_master` (`SC_MASTER_ID`)
) ENGINE=InnoDB;

CREATE TABLE `SCORE_PARAM_MASTER`(
  `SC_MASTER_ID` int  PRIMARY KEY NOT NULL,
  `CATEGORY_MASTER_ID_FK` int DEFAULT NULL,
  `COMPUTATION` varchar(255) DEFAULT NULL,
  `DATA_SOURCE` varchar(255) DEFAULT NULL,
  `DATA_TYPE` varchar(255) DEFAULT NULL,
  `DEFAULT_CRITERIA` varchar(255) DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `INTRASH` varchar(255) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
FOREIGN KEY (`CATEGORY_MASTER_ID_FK`) REFERENCES `score_category_master` (`SC_MASTER_ID`)
) ENGINE=InnoDB;

CREATE TABLE `SCORE_PARAM` (
  `SCORE_PARAM_ID` int PRIMARY KEY NOT NULL,
  `APPROVAL_LEVEL` int DEFAULT NULL,
  `APPROVAL_STATUS` int DEFAULT NULL,
  `COMPUTATION` varchar(255) DEFAULT NULL,
  `DATA_SOURCE` varchar(255) DEFAULT NULL,
  `DATA_TYPE` varchar(255) DEFAULT NULL,
  `INTRASH` varchar(255) DEFAULT NULL,
  `MASTER_PARAM_ID_FK` int DEFAULT NULL,
  `MAX_APPROVALS` int DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `PERCENTAGE_VALUE` int DEFAULT NULL,
  `SCORE_CATEGORY_ID_FK` int DEFAULT NULL,
  `UPDATE_CYCLE` int DEFAULT NULL,
FOREIGN KEY (`SCORE_CATEGORY_ID_FK`) REFERENCES `score_category` (`SCORE_CATEGORY_ID`),
FOREIGN KEY (`MASTER_PARAM_ID_FK`) REFERENCES `score_category_master` (`SC_MASTER_ID`)
) ENGINE=InnoDB ;

CREATE TABLE `SCORE_CARD` (
  `ID` int PRIMARY KEY NOT NULL,
  `APPROVAL_LEVEL` int DEFAULT NULL,
  `APPROVAL_STATUS` int DEFAULT NULL,
  `CRITERIA` varchar(255) DEFAULT NULL,
  `DATA_COLUMN` varchar(255) DEFAULT NULL,
  `DATA_SOURCE_ID_FK` int DEFAULT NULL,
  `INTRASH` varchar(255) DEFAULT NULL,
  `MAX_APPROVALS` int DEFAULT NULL,
  `SCORE_PARAM_ID_FK` int DEFAULT NULL,
  `UPDATE_CYCLE` int DEFAULT NULL,
FOREIGN KEY (`SCORE_PARAM_ID_FK`) REFERENCES `score_param` (`SCORE_PARAM_ID`)
) ENGINE=InnoDB ;

CREATE TABLE `api_users` (
  `USER_ID` int PRIMARY KEY NOT NULL AUTO_INCREMENT,
  `ACCESS_CHANNEL_ID` int DEFAULT NULL,
  `CREATE_DATE` datetime DEFAULT NULL,
  `FULL_NAME` varchar(255) DEFAULT NULL,
  `INTRASH` int DEFAULT NULL,
  `PASSWORD` varchar(255) DEFAULT NULL,
  `USERNAME` varchar(255) DEFAULT NULL,
  `ORGANISATION_ID_FK` int DEFAULT NULL,
FOREIGN KEY (`ORGANISATION_ID_FK`) REFERENCES `organisation` (`ORGANISATION_ID`)
) ENGINE=InnoDB AUTO_INCREMENT=13 ;

CREATE TABLE `Customer` (
  `CUSTOMER_ID` int PRIMARY KEY NOT NULL,
  `ACCOUNT_NUMBER` varchar(255) DEFAULT NULL,
  `ACTIVE_STATUS` varchar(255) DEFAULT NULL,
  `APPROVAL_LEVEL` int DEFAULT NULL,
  `APPROVAL_STATUS` int DEFAULT NULL,
  `BAD_CUSTOMER` int DEFAULT NULL,
  `CHANGE_PASSWORD` int DEFAULT NULL,
  `CITY` varchar(255) DEFAULT NULL,
  `COUNTRY` varchar(255) DEFAULT NULL,
  `CREATED_BY` int DEFAULT NULL,
  `CREDIT_SCORE_STATUS` int DEFAULT NULL,
  `CUSTOMER_TYPE` varchar(255) DEFAULT NULL,
  `DATE_CREATED` datetime DEFAULT NULL,
  `EMAIL` varchar(255) DEFAULT NULL,
  `FIRST_NAME` varchar(255) DEFAULT NULL,
  `GENDER` varchar(255) DEFAULT NULL,
  `ID_NUMBER` varchar(255) DEFAULT NULL,
  `INTRASH` varchar(255) DEFAULT NULL,
  `IS_NEW` varchar(255) DEFAULT NULL,
  `LAST_LOGIN_CHANGE` datetime DEFAULT NULL,
  `LAST_NAME` varchar(255) DEFAULT NULL,
  `LAST_PASSWORD_CHANGE` datetime DEFAULT NULL,
  `LOCKED` int DEFAULT NULL,
  `MAX_APPROVALS` int DEFAULT NULL,
  `MIDDLE_NAME` varchar(255) DEFAULT NULL,
  `MSISDN` varchar(255) DEFAULT NULL,
  `ORGANISATION_ID_FK` int DEFAULT NULL,
  `PASSWORD` varchar(255) DEFAULT NULL,
  `PIN` varchar(255) DEFAULT NULL,
  `PIN_STATUS` varchar(255) DEFAULT NULL,
  `REG_ON_CBS` varchar(255) DEFAULT NULL,
  `STREET` varchar(255) DEFAULT NULL,
  `TRX_CHANNEL` varchar(255) DEFAULT NULL,
  `UPDATE_CYCLE` int DEFAULT NULL,
  `USER_ID_FK` int DEFAULT NULL,
  `YOB` varchar(255) DEFAULT NULL,
FOREIGN KEY (`ORGANISATION_ID_FK`) REFERENCES `organisation` (`ORGANISATION_ID`),
FOREIGN KEY (`USER_ID_FK`) REFERENCES `api_users` (`USER_ID`)
) ENGINE=InnoDB ;

CREATE TABLE `Loan` (
  `LOAN_ID` int  PRIMARY KEY NOT NULL,
  `ACCOUNT_NO` varchar(255) DEFAULT NULL,
  `AMOUNT` double DEFAULT NULL,
  `APPROVAL_STATUS` varchar(255) DEFAULT NULL,
  `CBS_LOAN_NUMBER` varchar(255) DEFAULT NULL,
  `CHANNEL_ID` int DEFAULT NULL,
  `CREDIT_SCORE_LOG_ID` int DEFAULT NULL,
  `CUSTOMER_APPROVAL_LEVEL` int DEFAULT NULL,
  `CUSTOMER_APPROVALS` int DEFAULT NULL,
  `CUSTOMER_ID_FK` int DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `INTEREST` double DEFAULT NULL,
  `INTEREST_REPAID` double DEFAULT NULL,
  `INTEREST_TAKEN_UPFRONT` double DEFAULT NULL,
  `LAST_UPDATED` datetime DEFAULT NULL,
  `LOAN_BALANCE` double DEFAULT NULL,
  `LOAN_NUMBER` varchar(255) DEFAULT NULL,
  `LOAN_STATUS` varchar(255) DEFAULT NULL,
  `PARENT_ID` int DEFAULT NULL,
  `PERIOD` int DEFAULT NULL,
  `PRINCIPAL_REPAID` double DEFAULT NULL,
  `PROCESSING_STATUS` int DEFAULT NULL,
  `PRODUCT_ID_FK`int DEFAULT NULL,
  `REQUESTED_BY` int DEFAULT NULL,
  `TIME_APPROVED` datetime DEFAULT NULL,
  `TIME_INITIATED` datetime DEFAULT NULL,
  `TOTAL_CHARGES` double DEFAULT NULL,
  `TYPE` varchar(255) DEFAULT NULL,
FOREIGN KEY (`PRODUCT_ID_FK`) REFERENCES `product` (`PRODUCT_ID`),
FOREIGN KEY (`CUSTOMER_ID_FK`) REFERENCES `customer` (`CUSTOMER_ID`)
) ENGINE=InnoDB;

CREATE TABLE `Transaction` (
  `TRANSACTION_ID` int PRIMARY KEY NOT NULL,
  `AMOUNT` double DEFAULT NULL,
  `CONVERSATION_ID` varchar(255) DEFAULT NULL,
  `CUSTOMER_ID_FK` int DEFAULT NULL,
  `DISBURSEMENT_CHANNEL` int DEFAULT NULL,
  `FAIL_COUNT` int DEFAULT NULL,
  `INTERMEDIATE_STATUS` int DEFAULT NULL,
  `INTRASH` varchar(255) DEFAULT NULL,
  `LOAN_ID_FK` int DEFAULT NULL,
  `MSISDN` varchar(255) DEFAULT NULL,
  `ORIG_CONVERSATION_ID` varchar(255) DEFAULT NULL,
  `PRIMARY_PARTY` int DEFAULT NULL,
  `RECEIVER_PARTY` int DEFAULT NULL,
  `REFERENCE_ID` varchar(255) DEFAULT NULL,
  `SESSION_ID` varchar(255) DEFAULT NULL,
  `TIME_COMPLETED` datetime DEFAULT NULL,
  `TIME_INITIATED` datetime DEFAULT NULL,
  `TRX_ID` varchar(255) DEFAULT NULL,
  `TRX_STATUS` int DEFAULT NULL,
  `TRX_TYPE` varchar(255) DEFAULT NULL,
FOREIGN KEY (`CUSTOMER_ID_FK`) REFERENCES `customer` (`CUSTOMER_ID`),
FOREIGN KEY (`LOAN_ID_FK`) REFERENCES `loan` (`LOAN_ID`)
) ENGINE=InnoDB ;

CREATE TABLE `Channel` (
  `CHANNEL_ID` int PRIMARY KEY NOT NULL,
  `CHANNEL_MODE` varchar(255) DEFAULT NULL,
  `CHANNEL_TYPE` varchar(255) DEFAULT NULL,
  `CREATED_BY` varchar(255) DEFAULT NULL,
  `DATE_CREATED` date DEFAULT NULL,
  `DESCRIPTION` varchar(255) DEFAULT NULL,
  `INTRASH` varchar(255) DEFAULT NULL,
  `NAME` varchar(255) DEFAULT NULL,
  `PAYMENT_CHANNEL` varchar(255) DEFAULT NULL,
  `STATUS` int DEFAULT NULL
) ENGINE=InnoDB;



